// Runs every cases/*/repro.mjs against every installed SDK under ./sdk/ and writes the results matrix.
//
//   node run-all.mjs                       all cases x all installed SDK versions
//   node run-all.mjs --case T01            only cases whose id starts with T01
//   node run-all.mjs --sdk 2.15.0,2.16.0-next.17   only those SDK versions (comma-separated)
//   node run-all.mjs --quiet               print only the summary
//   node run-all.mjs --merge-only          run nothing; rebuild RESULTS.md from results/*.json
//
// Writes results/<platform>.json (this machine) and regenerates RESULTS.md from every results/*.json
// present, so a Windows run and a Linux run (scripts/run-linux.sh) end up side by side.
import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const arg = (name) => { const i = process.argv.indexOf(name); return i > 0 ? process.argv[i + 1] : null; };
const onlyCase = arg('--case');
const onlySdk = arg('--sdk') ? arg('--sdk').split(',') : null;
const quiet = process.argv.includes('--quiet');
const mergeOnly = process.argv.includes('--merge-only');
const platform = arg('--platform') || `${process.platform === 'win32' ? 'windows' : process.platform}-${process.arch}`;

const versions = readdirSync(join(ROOT, 'sdk'))
  .filter((v) => existsSync(join(ROOT, 'sdk', v, 'node_modules/@superdoc/sdk')))
  .filter((v) => !onlySdk || onlySdk.includes(v))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
const cases = readdirSync(join(ROOT, 'cases'))
  .filter((c) => existsSync(join(ROOT, 'cases', c, 'repro.mjs')))
  .filter((c) => !onlyCase || c.startsWith(onlyCase))
  .filter(() => !mergeOnly)
  .sort();

const rows = [];
for (const c of cases) {
  for (const v of versions) {
    const t0 = Date.now();
    const r = spawnSync(process.execPath, [join(ROOT, 'cases', c, 'repro.mjs'), v], { cwd: ROOT, encoding: 'utf8', timeout: 300_000 });
    const out = (r.stdout || '') + (r.stderr ? `[stderr]\n${r.stderr}` : '');
    if (!quiet) process.stdout.write(out + `[exit code ${r.status}]\n\n`);
    const line = out.split('\n').reverse().find((l) => l.startsWith('RESULT '));
    let parsed = null; try { parsed = line ? JSON.parse(line.slice(7)) : null; } catch { /* ignore */ }
    const verdict = r.status === 0 && parsed?.verdict === 'REPRODUCED' ? 'REPRODUCED'
      : r.status === 1 && parsed?.verdict === 'FIXED' ? 'FIXED'
      : 'ERROR';
    rows.push({ case: c, sdk: v, verdict, seconds: Math.round((Date.now() - t0) / 100) / 10, actual: parsed?.actual ?? parsed?.error ?? (r.error ? String(r.error) : `exit ${r.status}`) });
  }
}

mkdirSync(join(ROOT, 'results'), { recursive: true });
if (!mergeOnly) writeFileSync(join(ROOT, 'results', `${platform}.json`), JSON.stringify({ platform, node: process.version, date: new Date().toISOString(), rows }, null, 2) + '\n');

// Merge every platform file into RESULTS.md
const all = readdirSync(join(ROOT, 'results')).filter((f) => f.endsWith('.json')).map((f) => JSON.parse(readFileSync(join(ROOT, 'results', f), 'utf8')));
const columns = [];
for (const p of all) for (const row of p.rows) { const k = `${p.platform} · sdk ${row.sdk}`; if (!columns.includes(k)) columns.push(k); }
const caseIds = [...new Set(all.flatMap((p) => p.rows.map((x) => x.case)))].sort();
const mark = { REPRODUCED: 'BUG', FIXED: 'fixed', ERROR: 'error' };
let md = '# Results\n\nGenerated by `node run-all.mjs`. `BUG` = the behaviour in the case README reproduced (exit 0). `fixed` = the expected behaviour happened (exit 1). `error` = the script could not complete (exit 2).\n\n';
md += all.map((p) => `- **${p.platform}**: Node ${p.node}, run ${p.date}`).join('\n') + '\n\n';
md += `| Case | ${columns.join(' | ')} |\n| --- | ${columns.map(() => '---').join(' | ')} |\n`;
for (const c of caseIds) {
  md += `| [${c}](cases/${c}/README.md) | ${columns.map((col) => {
    const [plat, sdkPart] = col.split(' · sdk ');
    const hit = all.find((p) => p.platform === plat)?.rows.find((x) => x.case === c && x.sdk === sdkPart);
    return hit ? mark[hit.verdict] : '';
  }).join(' | ')} |\n`;
}
md += '\n## Actual outcome per run\n\n';
for (const p of all) {
  md += `### ${p.platform}\n\n| Case | SDK | Verdict | Actual |\n| --- | --- | --- | --- |\n`;
  for (const x of p.rows) md += `| ${x.case} | ${x.sdk} | ${mark[x.verdict]} | ${String(x.actual).replace(/\|/g, '\\|').replace(/\n/g, ' ')} |\n`;
  md += '\n';
}
writeFileSync(join(ROOT, 'RESULTS.md'), md);

console.log('='.repeat(100) + '\nSUMMARY (' + platform + ')');
for (const x of rows) console.log(`${x.case.padEnd(46)} sdk ${x.sdk.padEnd(16)} ${x.verdict.padEnd(11)} ${x.seconds}s`);
